name: Run Tests on Dev branches

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm i
       # Exécuter uniquement pour la branche dev
      if: github.ref == 'refs/heads/dev' 

    - name: Run tests
      run: npm run test
      # Exécuter uniquement pour la branche dev
      if: github.ref == 'refs/heads/dev'
